### ISSUE TITLE
First bug example ignores JavaScript

### ISSUE THREAD

**Issue by dtgriscom** [graphitemaster/fibers#2]
Your `upload_file()` example on locality of reference cited the loss of the `filename` argument reference. In JavaScript, what your code shows would be a closure, and would work just fine.

You might want to add a note to the effect of "JavaScript developers might not even have a bug here, as that language includes the concept of closures, where the `filename` reference would be preserved for the life of the anonymous function."

**Comment by graphitemaster** [comment]
Note added, thanks for the report.

**Comment by dtgriscom** [comment]
Looks good to me: thanks.
