### ISSUE TITLE
Microsoft x64 ABI

### ISSUE THREAD

**Issue by vasama** [graphitemaster/fibers#4]
XMM6-XMM15 are non-volatile in the Microsoft x64 ABI.
See https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=vs-2019#callercallee-saved-registers

**Comment by graphitemaster** [comment]
Fixed, thanks for the report.

**Comment by vasama** [comment]
XMM are 128-bit vector registers and cannot be stored in a pointer.

**Comment by graphitemaster** [comment]
I noticed that just myself, fix committed, thanks.

**Comment by graphitemaster** [comment]
Wrong instruction too, fixed as well.
